- name: run AWX on host
  hosts: localhost
  tasks:
    - name: import awx_pod role to install it all
      vars:
        awx_admin_user: admin
        awx_admin_password: foobar
        awx_podman_dir: /home/rsletten/data/awx
        awx_host_port: 8052
        container_state: running
      import_role:
        name: awx_pod
